language: node_js

node_js:
  - "node"

before_script:
  # - bash ./app setup
  - npm install -g gulp coffee-script easy-website-generator coffeelint bower
  - npm install
  # see https://github.com/sass/node-sass/issues/1804
  - npm rebuild node-sass

script:
  - bash ./app lint
  - bash ./app build
